#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="InventorySystem")]
	public partial class InventorySystemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdiscount(discount instance);
    partial void Updatediscount(discount instance);
    partial void Deletediscount(discount instance);
    partial void InsertdiscountProduct(discountProduct instance);
    partial void UpdatediscountProduct(discountProduct instance);
    partial void DeletediscountProduct(discountProduct instance);
    partial void Insertinventory(inventory instance);
    partial void Updateinventory(inventory instance);
    partial void Deleteinventory(inventory instance);
    partial void InsertorderItem(orderItem instance);
    partial void UpdateorderItem(orderItem instance);
    partial void DeleteorderItem(orderItem instance);
    partial void Insertorder(order instance);
    partial void Updateorder(order instance);
    partial void Deleteorder(order instance);
    partial void Insertproduct(product instance);
    partial void Updateproduct(product instance);
    partial void Deleteproduct(product instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void InsertuserRole(userRole instance);
    partial void UpdateuserRole(userRole instance);
    partial void DeleteuserRole(userRole instance);
    #endregion
		
		public InventorySystemDataContext() : 
				base(global::InventorySystem.Properties.Settings.Default.InventorySystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InventorySystemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventorySystemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventorySystemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventorySystemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<discount> discounts
		{
			get
			{
				return this.GetTable<discount>();
			}
		}
		
		public System.Data.Linq.Table<discountProduct> discountProducts
		{
			get
			{
				return this.GetTable<discountProduct>();
			}
		}
		
		public System.Data.Linq.Table<inventory> inventories
		{
			get
			{
				return this.GetTable<inventory>();
			}
		}
		
		public System.Data.Linq.Table<orderItem> orderItems
		{
			get
			{
				return this.GetTable<orderItem>();
			}
		}
		
		public System.Data.Linq.Table<order> orders
		{
			get
			{
				return this.GetTable<order>();
			}
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<userRole> userRoles
		{
			get
			{
				return this.GetTable<userRole>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.discount")]
	public partial class discount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _discountID;
		
		private string _name;
		
		private string _type;
		
		private decimal _value;
		
		private bool _active;
		
		private string _scope;
		
		private System.DateTime _startDate;
		
		private System.DateTime _endDate;
		
		private EntitySet<discountProduct> _discountProducts;
		
		private EntitySet<order> _orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndiscountIDChanging(int value);
    partial void OndiscountIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnvalueChanging(decimal value);
    partial void OnvalueChanged();
    partial void OnactiveChanging(bool value);
    partial void OnactiveChanged();
    partial void OnscopeChanging(string value);
    partial void OnscopeChanged();
    partial void OnstartDateChanging(System.DateTime value);
    partial void OnstartDateChanged();
    partial void OnendDateChanging(System.DateTime value);
    partial void OnendDateChanged();
    #endregion
		
		public discount()
		{
			this._discountProducts = new EntitySet<discountProduct>(new Action<discountProduct>(this.attach_discountProducts), new Action<discountProduct>(this.detach_discountProducts));
			this._orders = new EntitySet<order>(new Action<order>(this.attach_orders), new Action<order>(this.detach_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int discountID
		{
			get
			{
				return this._discountID;
			}
			set
			{
				if ((this._discountID != value))
				{
					this.OndiscountIDChanging(value);
					this.SendPropertyChanging();
					this._discountID = value;
					this.SendPropertyChanged("discountID");
					this.OndiscountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Decimal(18,2) NOT NULL")]
		public decimal value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit NOT NULL")]
		public bool active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scope", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string scope
		{
			get
			{
				return this._scope;
			}
			set
			{
				if ((this._scope != value))
				{
					this.OnscopeChanging(value);
					this.SendPropertyChanging();
					this._scope = value;
					this.SendPropertyChanged("scope");
					this.OnscopeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="Date NOT NULL")]
		public System.DateTime startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this.OnstartDateChanging(value);
					this.SendPropertyChanging();
					this._startDate = value;
					this.SendPropertyChanged("startDate");
					this.OnstartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="Date NOT NULL")]
		public System.DateTime endDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				if ((this._endDate != value))
				{
					this.OnendDateChanging(value);
					this.SendPropertyChanging();
					this._endDate = value;
					this.SendPropertyChanged("endDate");
					this.OnendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="discount_discountProduct", Storage="_discountProducts", ThisKey="discountID", OtherKey="discountID")]
		public EntitySet<discountProduct> discountProducts
		{
			get
			{
				return this._discountProducts;
			}
			set
			{
				this._discountProducts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="discount_order", Storage="_orders", ThisKey="discountID", OtherKey="discountID")]
		public EntitySet<order> orders
		{
			get
			{
				return this._orders;
			}
			set
			{
				this._orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_discountProducts(discountProduct entity)
		{
			this.SendPropertyChanging();
			entity.discount = this;
		}
		
		private void detach_discountProducts(discountProduct entity)
		{
			this.SendPropertyChanging();
			entity.discount = null;
		}
		
		private void attach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.discount = this;
		}
		
		private void detach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.discount = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.discountProduct")]
	public partial class discountProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _discountProductID;
		
		private int _discountID;
		
		private int _productID;
		
		private EntityRef<discount> _discount;
		
		private EntityRef<product> _product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndiscountProductIDChanging(int value);
    partial void OndiscountProductIDChanged();
    partial void OndiscountIDChanging(int value);
    partial void OndiscountIDChanged();
    partial void OnproductIDChanging(int value);
    partial void OnproductIDChanged();
    #endregion
		
		public discountProduct()
		{
			this._discount = default(EntityRef<discount>);
			this._product = default(EntityRef<product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountProductID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int discountProductID
		{
			get
			{
				return this._discountProductID;
			}
			set
			{
				if ((this._discountProductID != value))
				{
					this.OndiscountProductIDChanging(value);
					this.SendPropertyChanging();
					this._discountProductID = value;
					this.SendPropertyChanged("discountProductID");
					this.OndiscountProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountID", DbType="Int NOT NULL")]
		public int discountID
		{
			get
			{
				return this._discountID;
			}
			set
			{
				if ((this._discountID != value))
				{
					if (this._discount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndiscountIDChanging(value);
					this.SendPropertyChanging();
					this._discountID = value;
					this.SendPropertyChanged("discountID");
					this.OndiscountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int NOT NULL")]
		public int productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					if (this._product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="discount_discountProduct", Storage="_discount", ThisKey="discountID", OtherKey="discountID", IsForeignKey=true)]
		public discount discount
		{
			get
			{
				return this._discount.Entity;
			}
			set
			{
				discount previousValue = this._discount.Entity;
				if (((previousValue != value) 
							|| (this._discount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._discount.Entity = null;
						previousValue.discountProducts.Remove(this);
					}
					this._discount.Entity = value;
					if ((value != null))
					{
						value.discountProducts.Add(this);
						this._discountID = value.discountID;
					}
					else
					{
						this._discountID = default(int);
					}
					this.SendPropertyChanged("discount");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_discountProduct", Storage="_product", ThisKey="productID", OtherKey="productID", IsForeignKey=true)]
		public product product
		{
			get
			{
				return this._product.Entity;
			}
			set
			{
				product previousValue = this._product.Entity;
				if (((previousValue != value) 
							|| (this._product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product.Entity = null;
						previousValue.discountProducts.Remove(this);
					}
					this._product.Entity = value;
					if ((value != null))
					{
						value.discountProducts.Add(this);
						this._productID = value.productID;
					}
					else
					{
						this._productID = default(int);
					}
					this.SendPropertyChanged("product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.inventory")]
	public partial class inventory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _inventoryID;
		
		private int _productID;
		
		private int _quantity;
		
		private int _originalQuantity;
		
		private System.DateTime _receivedDate;
		
		private System.DateTime _manufacturingDate;
		
		private System.DateTime _expiryDate;
		
		private string _status;
		
		private EntitySet<orderItem> _orderItems;
		
		private EntityRef<product> _product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OninventoryIDChanging(int value);
    partial void OninventoryIDChanged();
    partial void OnproductIDChanging(int value);
    partial void OnproductIDChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    partial void OnoriginalQuantityChanging(int value);
    partial void OnoriginalQuantityChanged();
    partial void OnreceivedDateChanging(System.DateTime value);
    partial void OnreceivedDateChanged();
    partial void OnmanufacturingDateChanging(System.DateTime value);
    partial void OnmanufacturingDateChanged();
    partial void OnexpiryDateChanging(System.DateTime value);
    partial void OnexpiryDateChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public inventory()
		{
			this._orderItems = new EntitySet<orderItem>(new Action<orderItem>(this.attach_orderItems), new Action<orderItem>(this.detach_orderItems));
			this._product = default(EntityRef<product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inventoryID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int inventoryID
		{
			get
			{
				return this._inventoryID;
			}
			set
			{
				if ((this._inventoryID != value))
				{
					this.OninventoryIDChanging(value);
					this.SendPropertyChanging();
					this._inventoryID = value;
					this.SendPropertyChanged("inventoryID");
					this.OninventoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int NOT NULL")]
		public int productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					if (this._product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_originalQuantity", DbType="Int NOT NULL")]
		public int originalQuantity
		{
			get
			{
				return this._originalQuantity;
			}
			set
			{
				if ((this._originalQuantity != value))
				{
					this.OnoriginalQuantityChanging(value);
					this.SendPropertyChanging();
					this._originalQuantity = value;
					this.SendPropertyChanged("originalQuantity");
					this.OnoriginalQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivedDate", DbType="Date NOT NULL")]
		public System.DateTime receivedDate
		{
			get
			{
				return this._receivedDate;
			}
			set
			{
				if ((this._receivedDate != value))
				{
					this.OnreceivedDateChanging(value);
					this.SendPropertyChanging();
					this._receivedDate = value;
					this.SendPropertyChanged("receivedDate");
					this.OnreceivedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manufacturingDate", DbType="Date NOT NULL")]
		public System.DateTime manufacturingDate
		{
			get
			{
				return this._manufacturingDate;
			}
			set
			{
				if ((this._manufacturingDate != value))
				{
					this.OnmanufacturingDateChanging(value);
					this.SendPropertyChanging();
					this._manufacturingDate = value;
					this.SendPropertyChanged("manufacturingDate");
					this.OnmanufacturingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiryDate", DbType="Date NOT NULL")]
		public System.DateTime expiryDate
		{
			get
			{
				return this._expiryDate;
			}
			set
			{
				if ((this._expiryDate != value))
				{
					this.OnexpiryDateChanging(value);
					this.SendPropertyChanging();
					this._expiryDate = value;
					this.SendPropertyChanged("expiryDate");
					this.OnexpiryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="inventory_orderItem", Storage="_orderItems", ThisKey="inventoryID", OtherKey="inventoryID")]
		public EntitySet<orderItem> orderItems
		{
			get
			{
				return this._orderItems;
			}
			set
			{
				this._orderItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_inventory", Storage="_product", ThisKey="productID", OtherKey="productID", IsForeignKey=true)]
		public product product
		{
			get
			{
				return this._product.Entity;
			}
			set
			{
				product previousValue = this._product.Entity;
				if (((previousValue != value) 
							|| (this._product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product.Entity = null;
						previousValue.inventories.Remove(this);
					}
					this._product.Entity = value;
					if ((value != null))
					{
						value.inventories.Add(this);
						this._productID = value.productID;
					}
					else
					{
						this._productID = default(int);
					}
					this.SendPropertyChanged("product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orderItems(orderItem entity)
		{
			this.SendPropertyChanging();
			entity.inventory = this;
		}
		
		private void detach_orderItems(orderItem entity)
		{
			this.SendPropertyChanging();
			entity.inventory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orderItem")]
	public partial class orderItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _orderItemID;
		
		private int _orderID;
		
		private int _productID;
		
		private int _inventoryID;
		
		private int _quantity;
		
		private decimal _unitPrice;
		
		private decimal _total;
		
		private EntityRef<inventory> _inventory;
		
		private EntityRef<order> _order;
		
		private EntityRef<product> _product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorderItemIDChanging(int value);
    partial void OnorderItemIDChanged();
    partial void OnorderIDChanging(int value);
    partial void OnorderIDChanged();
    partial void OnproductIDChanging(int value);
    partial void OnproductIDChanged();
    partial void OninventoryIDChanging(int value);
    partial void OninventoryIDChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    partial void OnunitPriceChanging(decimal value);
    partial void OnunitPriceChanged();
    partial void OntotalChanging(decimal value);
    partial void OntotalChanged();
    #endregion
		
		public orderItem()
		{
			this._inventory = default(EntityRef<inventory>);
			this._order = default(EntityRef<order>);
			this._product = default(EntityRef<product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderItemID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int orderItemID
		{
			get
			{
				return this._orderItemID;
			}
			set
			{
				if ((this._orderItemID != value))
				{
					this.OnorderItemIDChanging(value);
					this.SendPropertyChanging();
					this._orderItemID = value;
					this.SendPropertyChanged("orderItemID");
					this.OnorderItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderID", DbType="Int NOT NULL")]
		public int orderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				if ((this._orderID != value))
				{
					if (this._order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnorderIDChanging(value);
					this.SendPropertyChanging();
					this._orderID = value;
					this.SendPropertyChanged("orderID");
					this.OnorderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int NOT NULL")]
		public int productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					if (this._product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inventoryID", DbType="Int NOT NULL")]
		public int inventoryID
		{
			get
			{
				return this._inventoryID;
			}
			set
			{
				if ((this._inventoryID != value))
				{
					if (this._inventory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OninventoryIDChanging(value);
					this.SendPropertyChanging();
					this._inventoryID = value;
					this.SendPropertyChanged("inventoryID");
					this.OninventoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitPrice", DbType="Decimal(18,2) NOT NULL")]
		public decimal unitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				if ((this._unitPrice != value))
				{
					this.OnunitPriceChanging(value);
					this.SendPropertyChanging();
					this._unitPrice = value;
					this.SendPropertyChanged("unitPrice");
					this.OnunitPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,2) NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="inventory_orderItem", Storage="_inventory", ThisKey="inventoryID", OtherKey="inventoryID", IsForeignKey=true)]
		public inventory inventory
		{
			get
			{
				return this._inventory.Entity;
			}
			set
			{
				inventory previousValue = this._inventory.Entity;
				if (((previousValue != value) 
							|| (this._inventory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._inventory.Entity = null;
						previousValue.orderItems.Remove(this);
					}
					this._inventory.Entity = value;
					if ((value != null))
					{
						value.orderItems.Add(this);
						this._inventoryID = value.inventoryID;
					}
					else
					{
						this._inventoryID = default(int);
					}
					this.SendPropertyChanged("inventory");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_orderItem", Storage="_order", ThisKey="orderID", OtherKey="orderID", IsForeignKey=true)]
		public order order
		{
			get
			{
				return this._order.Entity;
			}
			set
			{
				order previousValue = this._order.Entity;
				if (((previousValue != value) 
							|| (this._order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order.Entity = null;
						previousValue.orderItems.Remove(this);
					}
					this._order.Entity = value;
					if ((value != null))
					{
						value.orderItems.Add(this);
						this._orderID = value.orderID;
					}
					else
					{
						this._orderID = default(int);
					}
					this.SendPropertyChanged("order");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_orderItem", Storage="_product", ThisKey="productID", OtherKey="productID", IsForeignKey=true)]
		public product product
		{
			get
			{
				return this._product.Entity;
			}
			set
			{
				product previousValue = this._product.Entity;
				if (((previousValue != value) 
							|| (this._product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product.Entity = null;
						previousValue.orderItems.Remove(this);
					}
					this._product.Entity = value;
					if ((value != null))
					{
						value.orderItems.Add(this);
						this._productID = value.productID;
					}
					else
					{
						this._productID = default(int);
					}
					this.SendPropertyChanged("product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orders")]
	public partial class order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _orderID;
		
		private int _userID;
		
		private System.DateTime _date;
		
		private decimal _grossTotal;
		
		private decimal _discountTotal;
		
		private decimal _tax;
		
		private decimal _netTotal;
		
		private int _discountID;
		
		private EntitySet<orderItem> _orderItems;
		
		private EntityRef<discount> _discount;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorderIDChanging(int value);
    partial void OnorderIDChanged();
    partial void OnuserIDChanging(int value);
    partial void OnuserIDChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OngrossTotalChanging(decimal value);
    partial void OngrossTotalChanged();
    partial void OndiscountTotalChanging(decimal value);
    partial void OndiscountTotalChanged();
    partial void OntaxChanging(decimal value);
    partial void OntaxChanged();
    partial void OnnetTotalChanging(decimal value);
    partial void OnnetTotalChanged();
    partial void OndiscountIDChanging(int value);
    partial void OndiscountIDChanged();
    #endregion
		
		public order()
		{
			this._orderItems = new EntitySet<orderItem>(new Action<orderItem>(this.attach_orderItems), new Action<orderItem>(this.detach_orderItems));
			this._discount = default(EntityRef<discount>);
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int orderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				if ((this._orderID != value))
				{
					this.OnorderIDChanging(value);
					this.SendPropertyChanging();
					this._orderID = value;
					this.SendPropertyChanged("orderID");
					this.OnorderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Int NOT NULL")]
		public int userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grossTotal", DbType="Decimal(18,2) NOT NULL")]
		public decimal grossTotal
		{
			get
			{
				return this._grossTotal;
			}
			set
			{
				if ((this._grossTotal != value))
				{
					this.OngrossTotalChanging(value);
					this.SendPropertyChanging();
					this._grossTotal = value;
					this.SendPropertyChanged("grossTotal");
					this.OngrossTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountTotal", DbType="Decimal(18,2) NOT NULL")]
		public decimal discountTotal
		{
			get
			{
				return this._discountTotal;
			}
			set
			{
				if ((this._discountTotal != value))
				{
					this.OndiscountTotalChanging(value);
					this.SendPropertyChanging();
					this._discountTotal = value;
					this.SendPropertyChanged("discountTotal");
					this.OndiscountTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tax", DbType="Decimal(18,2) NOT NULL")]
		public decimal tax
		{
			get
			{
				return this._tax;
			}
			set
			{
				if ((this._tax != value))
				{
					this.OntaxChanging(value);
					this.SendPropertyChanging();
					this._tax = value;
					this.SendPropertyChanged("tax");
					this.OntaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_netTotal", DbType="Decimal(18,2) NOT NULL")]
		public decimal netTotal
		{
			get
			{
				return this._netTotal;
			}
			set
			{
				if ((this._netTotal != value))
				{
					this.OnnetTotalChanging(value);
					this.SendPropertyChanging();
					this._netTotal = value;
					this.SendPropertyChanged("netTotal");
					this.OnnetTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountID", DbType="Int NOT NULL")]
		public int discountID
		{
			get
			{
				return this._discountID;
			}
			set
			{
				if ((this._discountID != value))
				{
					if (this._discount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndiscountIDChanging(value);
					this.SendPropertyChanging();
					this._discountID = value;
					this.SendPropertyChanged("discountID");
					this.OndiscountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_orderItem", Storage="_orderItems", ThisKey="orderID", OtherKey="orderID")]
		public EntitySet<orderItem> orderItems
		{
			get
			{
				return this._orderItems;
			}
			set
			{
				this._orderItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="discount_order", Storage="_discount", ThisKey="discountID", OtherKey="discountID", IsForeignKey=true)]
		public discount discount
		{
			get
			{
				return this._discount.Entity;
			}
			set
			{
				discount previousValue = this._discount.Entity;
				if (((previousValue != value) 
							|| (this._discount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._discount.Entity = null;
						previousValue.orders.Remove(this);
					}
					this._discount.Entity = value;
					if ((value != null))
					{
						value.orders.Add(this);
						this._discountID = value.discountID;
					}
					else
					{
						this._discountID = default(int);
					}
					this.SendPropertyChanged("discount");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_order", Storage="_user", ThisKey="userID", OtherKey="userID", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.orders.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.orders.Add(this);
						this._userID = value.userID;
					}
					else
					{
						this._userID = default(int);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orderItems(orderItem entity)
		{
			this.SendPropertyChanging();
			entity.order = this;
		}
		
		private void detach_orderItems(orderItem entity)
		{
			this.SendPropertyChanging();
			entity.order = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
	public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _productID;
		
		private string _name;
		
		private string _description;
		
		private string _type;
		
		private decimal _cost;
		
		private decimal _sellingPrice;
		
		private int _reoderLevel;
		
		private string _image;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _deletedDate;
		
		private EntitySet<discountProduct> _discountProducts;
		
		private EntitySet<inventory> _inventories;
		
		private EntitySet<orderItem> _orderItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductIDChanging(int value);
    partial void OnproductIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OncostChanging(decimal value);
    partial void OncostChanged();
    partial void OnsellingPriceChanging(decimal value);
    partial void OnsellingPriceChanged();
    partial void OnreoderLevelChanging(int value);
    partial void OnreoderLevelChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OndeletedDateChanging(System.Nullable<System.DateTime> value);
    partial void OndeletedDateChanged();
    #endregion
		
		public product()
		{
			this._discountProducts = new EntitySet<discountProduct>(new Action<discountProduct>(this.attach_discountProducts), new Action<discountProduct>(this.detach_discountProducts));
			this._inventories = new EntitySet<inventory>(new Action<inventory>(this.attach_inventories), new Action<inventory>(this.detach_inventories));
			this._orderItems = new EntitySet<orderItem>(new Action<orderItem>(this.attach_orderItems), new Action<orderItem>(this.detach_orderItems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int productID
		{
			get
			{
				return this._productID;
			}
			set
			{
				if ((this._productID != value))
				{
					this.OnproductIDChanging(value);
					this.SendPropertyChanging();
					this._productID = value;
					this.SendPropertyChanged("productID");
					this.OnproductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost", DbType="Decimal(18,2) NOT NULL")]
		public decimal cost
		{
			get
			{
				return this._cost;
			}
			set
			{
				if ((this._cost != value))
				{
					this.OncostChanging(value);
					this.SendPropertyChanging();
					this._cost = value;
					this.SendPropertyChanged("cost");
					this.OncostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sellingPrice", DbType="Decimal(18,2) NOT NULL")]
		public decimal sellingPrice
		{
			get
			{
				return this._sellingPrice;
			}
			set
			{
				if ((this._sellingPrice != value))
				{
					this.OnsellingPriceChanging(value);
					this.SendPropertyChanging();
					this._sellingPrice = value;
					this.SendPropertyChanged("sellingPrice");
					this.OnsellingPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reoderLevel", DbType="Int NOT NULL")]
		public int reoderLevel
		{
			get
			{
				return this._reoderLevel;
			}
			set
			{
				if ((this._reoderLevel != value))
				{
					this.OnreoderLevelChanging(value);
					this.SendPropertyChanging();
					this._reoderLevel = value;
					this.SendPropertyChanged("reoderLevel");
					this.OnreoderLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(20)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deletedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> deletedDate
		{
			get
			{
				return this._deletedDate;
			}
			set
			{
				if ((this._deletedDate != value))
				{
					this.OndeletedDateChanging(value);
					this.SendPropertyChanging();
					this._deletedDate = value;
					this.SendPropertyChanged("deletedDate");
					this.OndeletedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_discountProduct", Storage="_discountProducts", ThisKey="productID", OtherKey="productID")]
		public EntitySet<discountProduct> discountProducts
		{
			get
			{
				return this._discountProducts;
			}
			set
			{
				this._discountProducts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_inventory", Storage="_inventories", ThisKey="productID", OtherKey="productID")]
		public EntitySet<inventory> inventories
		{
			get
			{
				return this._inventories;
			}
			set
			{
				this._inventories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_orderItem", Storage="_orderItems", ThisKey="productID", OtherKey="productID")]
		public EntitySet<orderItem> orderItems
		{
			get
			{
				return this._orderItems;
			}
			set
			{
				this._orderItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_discountProducts(discountProduct entity)
		{
			this.SendPropertyChanging();
			entity.product = this;
		}
		
		private void detach_discountProducts(discountProduct entity)
		{
			this.SendPropertyChanging();
			entity.product = null;
		}
		
		private void attach_inventories(inventory entity)
		{
			this.SendPropertyChanging();
			entity.product = this;
		}
		
		private void detach_inventories(inventory entity)
		{
			this.SendPropertyChanging();
			entity.product = null;
		}
		
		private void attach_orderItems(orderItem entity)
		{
			this.SendPropertyChanging();
			entity.product = this;
		}
		
		private void detach_orderItems(orderItem entity)
		{
			this.SendPropertyChanging();
			entity.product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userID;
		
		private string _firstName;
		
		private string _lastName;
		
		private string _userName;
		
		private string _password;
		
		private int _roleID;
		
		private string _contactNumber;
		
		private System.Nullable<System.DateTime> _dateCreated;
		
		private string _assignedShift;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _deletedDate;
		
		private EntitySet<order> _orders;
		
		private EntityRef<userRole> _userRole;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(int value);
    partial void OnuserIDChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleIDChanging(int value);
    partial void OnroleIDChanged();
    partial void OncontactNumberChanging(string value);
    partial void OncontactNumberChanged();
    partial void OndateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OndateCreatedChanged();
    partial void OnassignedShiftChanging(string value);
    partial void OnassignedShiftChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OndeletedDateChanging(System.Nullable<System.DateTime> value);
    partial void OndeletedDateChanged();
    #endregion
		
		public user()
		{
			this._orders = new EntitySet<order>(new Action<order>(this.attach_orders), new Action<order>(this.detach_orders));
			this._userRole = default(EntityRef<userRole>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleID", DbType="Int NOT NULL")]
		public int roleID
		{
			get
			{
				return this._roleID;
			}
			set
			{
				if ((this._roleID != value))
				{
					if (this._userRole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnroleIDChanging(value);
					this.SendPropertyChanging();
					this._roleID = value;
					this.SendPropertyChanged("roleID");
					this.OnroleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="NVarChar(20)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this.OncontactNumberChanging(value);
					this.SendPropertyChanging();
					this._contactNumber = value;
					this.SendPropertyChanged("contactNumber");
					this.OncontactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if ((this._dateCreated != value))
				{
					this.OndateCreatedChanging(value);
					this.SendPropertyChanging();
					this._dateCreated = value;
					this.SendPropertyChanged("dateCreated");
					this.OndateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assignedShift", DbType="NVarChar(50)")]
		public string assignedShift
		{
			get
			{
				return this._assignedShift;
			}
			set
			{
				if ((this._assignedShift != value))
				{
					this.OnassignedShiftChanging(value);
					this.SendPropertyChanging();
					this._assignedShift = value;
					this.SendPropertyChanged("assignedShift");
					this.OnassignedShiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(20)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deletedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> deletedDate
		{
			get
			{
				return this._deletedDate;
			}
			set
			{
				if ((this._deletedDate != value))
				{
					this.OndeletedDateChanging(value);
					this.SendPropertyChanging();
					this._deletedDate = value;
					this.SendPropertyChanged("deletedDate");
					this.OndeletedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_order", Storage="_orders", ThisKey="userID", OtherKey="userID")]
		public EntitySet<order> orders
		{
			get
			{
				return this._orders;
			}
			set
			{
				this._orders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="userRole_user", Storage="_userRole", ThisKey="roleID", OtherKey="roleID", IsForeignKey=true)]
		public userRole userRole
		{
			get
			{
				return this._userRole.Entity;
			}
			set
			{
				userRole previousValue = this._userRole.Entity;
				if (((previousValue != value) 
							|| (this._userRole.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._userRole.Entity = null;
						previousValue.users.Remove(this);
					}
					this._userRole.Entity = value;
					if ((value != null))
					{
						value.users.Add(this);
						this._roleID = value.roleID;
					}
					else
					{
						this._roleID = default(int);
					}
					this.SendPropertyChanged("userRole");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userRole")]
	public partial class userRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _roleID;
		
		private string _roleName;
		
		private EntitySet<user> _users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnroleIDChanging(int value);
    partial void OnroleIDChanged();
    partial void OnroleNameChanging(string value);
    partial void OnroleNameChanged();
    #endregion
		
		public userRole()
		{
			this._users = new EntitySet<user>(new Action<user>(this.attach_users), new Action<user>(this.detach_users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int roleID
		{
			get
			{
				return this._roleID;
			}
			set
			{
				if ((this._roleID != value))
				{
					this.OnroleIDChanging(value);
					this.SendPropertyChanging();
					this._roleID = value;
					this.SendPropertyChanged("roleID");
					this.OnroleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string roleName
		{
			get
			{
				return this._roleName;
			}
			set
			{
				if ((this._roleName != value))
				{
					this.OnroleNameChanging(value);
					this.SendPropertyChanging();
					this._roleName = value;
					this.SendPropertyChanged("roleName");
					this.OnroleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="userRole_user", Storage="_users", ThisKey="roleID", OtherKey="roleID")]
		public EntitySet<user> users
		{
			get
			{
				return this._users;
			}
			set
			{
				this._users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_users(user entity)
		{
			this.SendPropertyChanging();
			entity.userRole = this;
		}
		
		private void detach_users(user entity)
		{
			this.SendPropertyChanging();
			entity.userRole = null;
		}
	}
}
#pragma warning restore 1591
